name: ${artifactId}
main: ${package}.${artifactId}
version: ${version}

commands:
  command:
    description: A Command
    usage: /<command>
permissions:
  ${artifactId}.*:
    description: A description
    children:
      ${artifactId}.test: true
  ${artifactId}.test:
    description: Test Permission
    default: op