name: ${artifactId}
main: ${package}.${artifactId}
version: ${project.version}
author: Infernal Development

commands:
  test:
    description: A Command
    usage: /<command>
permissions:
  ${artifactId}.*:
    description: A description
    children:
      ${artifactId}.test: true
  ${artifactId}.test:
    description: Test Permission
    default: op